[[redirects]]
  from = "/the-difference-between-our-bespoke-orthotics-and-our-custom-insoles/"
  to = "/blog/the-difference-between-our-bespoke-orthotics-and-our-custom-insoles/"
  status = 301
  force = true
 [[redirects]]
  from = "/the-impact-of-ageing-on-feet-and-the-role-of-orthotics/"
  to = "/blog/the-impact-of-ageing-on-feet-and-the-role-of-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/give-the-gift-of-comfort-this-christmas/"
  to = "/blog/give-the-gift-of-comfort-this-christmas/"
  status = 301
  force = true
 [[redirects]]
  from = "/give-your-old-ski-boots-a-second-chance/"
  to = "/blog/give-your-old-ski-boots-a-second-chance/"
  status = 301
  force = true
 [[redirects]]
  from = "/five-of-the-best-winter-hiking-trails-near-london/"
  to = "/blog/five-of-the-best-winter-hiking-trails-near-london/"
  status = 301
  force = true
 [[redirects]]
  from = "/bespoke-orthotics-in-football-enhancing-performance-and-preventing-injury/"
  to = "/blog/bespoke-orthotics-in-football-enhancing-performance-and-preventing-injury/"
  status = 301
  force = true
 [[redirects]]
  from = "/understanding-plantar-fasciitis-causes-symptoms-and-treatment/"
  to = "/blog/understanding-plantar-fasciitis-causes-symptoms-and-treatment/"
  status = 301
  force = true
 [[redirects]]
  from = "/your-orthotics-appointment-what-to-expect/"
  to = "/blog/your-orthotics-appointment-what-to-expect/"
  status = 301
  force = true
 [[redirects]]
  from = "/running-orthotics-explained/"
  to = "/blog/running-orthotics-explained/"
  status = 301
  force = true
 [[redirects]]
  from = "/benefits-of-bespoke-orthotics-for-golfers/"
  to = "/blog/benefits-of-bespoke-orthotics-for-golfers/"
  status = 301
  force = true
 [[redirects]]
  from = "/bespoke-orthotics-for-hip-and-pelvic-pain/"
  to = "/blog/bespoke-orthotics-for-hip-and-pelvic-pain/"
  status = 301
  force = true
 [[redirects]]
  from = "/choosing-the-right-footwear-for-your-holiday/"
  to = "/blog/choosing-the-right-footwear-for-your-holiday/"
  status = 301
  force = true
 [[redirects]]
  from = "/is-under-or-over-pronation-the-cause-of-your-running-injuries/"
  to = "/blog/is-under-or-over-pronation-the-cause-of-your-running-injuries/"
  status = 301
  force = true
 [[redirects]]
  from = "/bespoke-hiking-orthotics/"
  to = "/blog/bespoke-hiking-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/how-orthotics-can-aid-in-acl-injury-recovery/"
  to = "/blog/how-orthotics-can-aid-in-acl-injury-recovery/"
  status = 301
  force = true
 [[redirects]]
  from = "/exploring-the-best-spring-hiking-trails-in-the-uk/"
  to = "/blog/exploring-the-best-spring-hiking-trails-in-the-uk/"
  status = 301
  force = true
 [[redirects]]
  from = "/finding-relief-how-bespoke-orthotics-alleviate-bunion-pain/"
  to = "/blog/finding-relief-how-bespoke-orthotics-alleviate-bunion-pain/"
  status = 301
  force = true
 [[redirects]]
  from = "/orthotics-for-pregnancy/"
  to = "/blog/orthotics-for-pregnancy/"
  status = 301
  force = true
 [[redirects]]
  from = "/tendonitis-orthotics/"
  to = "/blog/tendonitis-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/preparing-for-the-london-marathon-2024/"
  to = "/blog/preparing-for-the-london-marathon-2024/"
  status = 301
  force = true
 [[redirects]]
  from = "/arch-support-orthotics-for-flat-feet/"
  to = "/blog/arch-support-orthotics-for-flat-feet/"
  status = 301
  force = true
 [[redirects]]
  from = "/orthotics-for-ski-orthotics/"
  to = "/blog/orthotics-for-ski-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/the-importance-of-bespoke-orthotics-in-your-ski-boots/"
  to = "/blog/the-importance-of-bespoke-orthotics-in-your-ski-boots/"
  status = 301
  force = true
 [[redirects]]
  from = "/gift-vouchers-2023/"
  to = "/blog/gift-vouchers-2023/"
  status = 301
  force = true
 [[redirects]]
  from = "/bespoke-orthotics-for-rugby-football-players/"
  to = "/blog/bespoke-orthotics-for-rugby-football-players/"
  status = 301
  force = true
 [[redirects]]
  from = "/best-hiking-trails-uk-autumn/"
  to = "/blog/best-hiking-trails-uk-autumn/"
  status = 301
  force = true
 [[redirects]]
  from = "/solution-for-runners-with-overpronation/"
  to = "/blog/solution-for-runners-with-overpronation/"
  status = 301
  force = true
 [[redirects]]
  from = "/back-to-school-orthotics/"
  to = "/blog/back-to-school-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/the-hidden-edge-custom-orthotics-for-golfers/"
  to = "/blog/the-hidden-edge-custom-orthotics-for-golfers/"
  status = 301
  force = true
 [[redirects]]
  from = "/hiking-orthotics/"
  to = "/blog/hiking-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/the-best-shoes-and-orthotics-for-walking-to-work/"
  to = "/blog/the-best-shoes-and-orthotics-for-walking-to-work/"
  status = 301
  force = true
 [[redirects]]
  from = "/hiking-trails-near-london/"
  to = "/blog/hiking-trails-near-london/"
  status = 301
  force = true
 [[redirects]]
  from = "/cycling-orthotics/"
  to = "/blog/cycling-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/norberts-fundraising-for-ataxia/"
  to = "/blog/norberts-fundraising-for-ataxia/"
  status = 301
  force = true
 [[redirects]]
  from = "/can-bespoke-orthotics-help-my-tennis/"
  to = "/blog/can-bespoke-orthotics-help-my-tennis/"
  status = 301
  force = true
 [[redirects]]
  from = "/overpronation/"
  to = "/blog/overpronation/"
  status = 301
  force = true
 [[redirects]]
  from = "/london-lions/"
  to = "/blog/london-lions/"
  status = 301
  force = true
 [[redirects]]
  from = "/introducing-hugo-cauvas-our-technical-director/"
  to = "/blog/introducing-hugo-cauvas-our-technical-director/"
  status = 301
  force = true
 [[redirects]]
  from = "/new-semi-custom-orthotics-for-all/"
  to = "/blog/new-semi-custom-orthotics-for-all/"
  status = 301
  force = true
 [[redirects]]
  from = "/seasons-greetings-from-foot-factor/"
  to = "/blog/seasons-greetings-from-foot-factor/"
  status = 301
  force = true
 [[redirects]]
  from = "/gift-vouchers/"
  to = "/blog/gift-vouchers/"
  status = 301
  force = true
 [[redirects]]
  from = "/patellofemoral-pain/"
  to = "/blog/patellofemoral-pain/"
  status = 301
  force = true
 [[redirects]]
  from = "/seasons-greetings/"
  to = "/blog/seasons-greetings/"
  status = 301
  force = true
 [[redirects]]
  from = "/case-studies-common-ski-issues/"
  to = "/blog/case-studies-common-ski-issues/"
  status = 301
  force = true
 [[redirects]]
  from = "/ski-definition/"
  to = "/blog/ski-definition/"
  status = 301
  force = true
 [[redirects]]
  from = "/ski-orthotics/"
  to = "/blog/ski-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/case-studies-knee-pain-patellofemoral-pain/"
  to = "/blog/case-studies-knee-pain-patellofemoral-pain/"
  status = 301
  force = true
 [[redirects]]
  from = "/london-marathon-2021/"
  to = "/blog/london-marathon-2021/"
  status = 301
  force = true
 [[redirects]]
  from = "/podiatrist-amy-curran-joins-foot-factor/"
  to = "/blog/podiatrist-amy-curran-joins-foot-factor/"
  status = 301
  force = true
 [[redirects]]
  from = "/case-studies-arch-pain-plantar-fasciitis-treatment/"
  to = "/blog/case-studies-arch-pain-plantar-fasciitis-treatment/"
  status = 301
  force = true
 [[redirects]]
  from = "/from-wimbledon-to-euro-2020-to-the-olympics-orthotics/"
  to = "/blog/from-wimbledon-to-euro-2020-to-the-olympics-orthotics/"
  status = 301
  force = true
 [[redirects]]
  from = "/this-green-and-pleasant-land-staycation/"
  to = "/blog/this-green-and-pleasant-land-staycation/"
  status = 301
  force = true
 [[redirects]]
  from = "/heel-pain-holding-you-back/"
  to = "/blog/heel-pain-holding-you-back/"
  status = 301
  force = true
 [[redirects]]
  from = "/matthew-collison-joins-the-foot-factor-team/"
  to = "/blog/matthew-collison-joins-the-foot-factor-team/"
  status = 301
  force = true
 [[redirects]]
  from = "/walking-for-wellbeing/"
  to = "/blog/walking-for-wellbeing/"
  status = 301
  force = true
 [[redirects]]
  from = "/all-i-want-for-christmas-is-happy-feet/"
  to = "/blog/all-i-want-for-christmas-is-happy-feet/"
  status = 301
  force = true
 [[redirects]]
  from = "/foot-factor-sidas-concept/"
  to = "/blog/foot-factor-sidas-concept/"
  status = 301
  force = true
 [[redirects]]
  from = "/anterior-knee-pain-patella-femoral-syndrome-runners-knee/"
  to = "/blog/anterior-knee-pain-patella-femoral-syndrome-runners-knee/"
  status = 301
  force = true
 [[redirects]]
  from = "/connection-feet-posture/"
  to = "/blog/connection-feet-posture/"
  status = 301
  force = true
 [[redirects]]
  from = "/plantar-fasciitis/"
  to = "/blog/plantar-fasciitis/"
  status = 301
  force = true
 [[redirects]]
  from = "/shin-splints/"
  to = "/blog/shin-splints/"
  status = 301
  force = true
 [[redirects]]
  from = "/evaluation-sports-plantar-orthotics-running/"
  to = "/blog/evaluation-sports-plantar-orthotics-running/"
  status = 301
  force = true
 [[redirects]]
  from = "/foot-factors-way-working/"
  to = "/blog/foot-factors-way-working/"
  status = 301
  force = true
 [[redirects]]
  from = "/ski-boots-fitting-problems/"
  to = "/blog/ski-boots-fitting-problems/"
  status = 301
  force = true
 