// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  call_to_action: dynamic(() => import('./CallToAction')),
  faqs: dynamic(() => import('./Faqs')),
  hero: dynamic(() => import('./Hero')),
  megamenu: dynamic(() => import('./Megamenu')),
  section: dynamic(() => import('./Section')),
  testimonial: dynamic(() => import('./Testimonial')),
};
